export { default as Dashboard } from './Dashboard';
export {default as Landing } from './Landing'; 
export {default as Aim } from './Aim'; 
export {default as Contactus } from './Contactus'; 
export {default as Event1 } from './Event1'; 
export {default as Event2 } from './Event2'; 
export {default as Home } from './Home'; 
export {default as Tests } from './Tests'; 
export {default as Report } from './Report'; 
export {default as Service1 } from './Service1'; 
export {default as Service2 } from './Service2'; 
export {default as Support } from './Support'; 
export {default as Vision } from './Vision'; 
